language: node_js
node_js:
    - "0.10"
env:
    global:
        - NODE_ENV=test
        - TEST_ENV=travis
services:
    - couchdb

before_install:
    # make sudoer use same PATH than default user (includes npm & node)
    - npm -g install coffee-script
    - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers
    - env | grep PATH
    - sudo env | grep PATH

script: "TEST_ENV=travis sudo npm test"
